import { WifiDevice, ThreatLevel } from '../types';

export const generateKML = (devices: WifiDevice[]): string => {
  const trackedDevices = devices.filter(d => d.gps);
  
  if (trackedDevices.length === 0) {
    return '';
  }

  const kmlHeader = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>CYT Surveillance Export</name>
    <description>Generated by Chasing Your Tail Touch</description>
    
    <!-- STYLES -->
    <Style id="icon-high">
      <IconStyle>
        <color>ff0000ff</color>
        <scale>1.2</scale>
        <Icon><href>http://maps.google.com/mapfiles/kml/shapes/target.png</href></Icon>
      </IconStyle>
      <LineStyle>
        <color>ff0000ff</color>
        <width>4</width>
      </LineStyle>
    </Style>
    
    <Style id="icon-suspicious">
      <IconStyle>
        <color>ff00ffff</color>
        <scale>1.0</scale>
        <Icon><href>http://maps.google.com/mapfiles/kml/shapes/caution.png</href></Icon>
      </IconStyle>
      <LineStyle>
        <color>ff00ffff</color>
        <width>3</width>
      </LineStyle>
    </Style>

    <Style id="icon-safe">
      <IconStyle>
        <color>ff00ff00</color>
        <scale>0.8</scale>
        <Icon><href>http://maps.google.com/mapfiles/kml/paddle/wht-blank.png</href></Icon>
      </IconStyle>
      <LineStyle>
        <color>ff00ff00</color>
        <width>2</width>
      </LineStyle>
    </Style>
`;

  const kmlFooter = `
  </Document>
</kml>`;

  const placemarks = trackedDevices.map(d => {
    // Determine Style
    let styleId = '#icon-safe';
    if (d.threatLevel === ThreatLevel.HIGH) styleId = '#icon-high';
    else if (d.threatLevel === ThreatLevel.SUSPICIOUS) styleId = '#icon-suspicious';

    // Rich HTML Description
    const description = `<![CDATA[
      <div style="font-family: sans-serif; width: 300px;">
        <h2 style="margin:0; border-bottom: 2px solid #ccc; padding-bottom: 5px;">${d.ssid || d.mac}</h2>
        <table style="width: 100%; margin-top: 10px;">
          <tr><td><strong>MAC:</strong></td><td>${d.mac}</td></tr>
          <tr><td><strong>Vendor:</strong></td><td>${d.vendor || 'Unknown'}</td></tr>
          <tr><td><strong>Type:</strong></td><td>${d.type}</td></tr>
          <tr><td><strong>Threat:</strong></td><td style="color:${d.threatLevel === 'High' ? 'red' : 'black'}"><strong>${d.threatLevel}</strong></td></tr>
          <tr><td><strong>Persistence:</strong></td><td>${Math.round(d.persistenceScore * 100)}%</td></tr>
          <tr><td><strong>First Seen:</strong></td><td>${new Date(d.firstSeen).toLocaleString()}</td></tr>
          <tr><td><strong>Last Seen:</strong></td><td>${new Date(d.lastSeen).toLocaleString()}</td></tr>
        </table>
        ${d.probedSSIDs.length > 0 ? `
          <div style="margin-top: 10px; background: #eee; padding: 5px; border-radius: 4px;">
            <strong>Probing For:</strong><br/>
            ${d.probedSSIDs.join(', ')}
          </div>
        ` : ''}
        ${d.notes ? `<p style="color:red; font-weight:bold;">NOTES: ${d.notes}</p>` : ''}
      </div>
    ]]>`;

    // 1. The Main Point (Last Known Location)
    const pointPlacemark = `
    <Placemark>
      <name>${d.ssid || d.mac}</name>
      <description>${description}</description>
      <styleUrl>${styleId}</styleUrl>
      <Point>
        <coordinates>${d.gps?.lng},${d.gps?.lat},0</coordinates>
      </Point>
    </Placemark>`;

    // 2. The Tracking Path (LineString) - If history exists
    let pathPlacemark = '';
    if (d.gpsHistory && d.gpsHistory.length > 1) {
       const coordinates = d.gpsHistory.map(p => `${p.lng},${p.lat},0`).join(' ');
       pathPlacemark = `
       <Placemark>
         <name>Path: ${d.ssid || d.mac}</name>
         <styleUrl>${styleId}</styleUrl>
         <LineString>
           <tessellate>1</tessellate>
           <coordinates>${coordinates}</coordinates>
         </LineString>
       </Placemark>`;
    }

    return pointPlacemark + pathPlacemark;
  }).join('');

  return kmlHeader + placemarks + kmlFooter;
};

export const downloadKML = (devices: WifiDevice[]) => {
  const content = generateKML(devices);
  if (!content) {
    alert("No devices with GPS data to export.");
    return;
  }
  
  const blob = new Blob([content], { type: 'application/vnd.google-earth.kml+xml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `cyt-scan-${new Date().toISOString().slice(0,19).replace(/:/g,'-')}.kml`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};