import { WifiDevice, ThreatLevel } from '../types';

export const generateKML = (devices: WifiDevice[]): string => {
  const trackedDevices = devices.filter(d => d.gps);
  
  if (trackedDevices.length === 0) {
    return '';
  }

  const kmlHeader = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>CYT Surveillance Export</name>
    <description>Generated by Chasing Your Tail Touch</description>
    <Style id="highThreat">
      <IconStyle>
        <color>ff0000ff</color>
        <scale>1.2</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/shapes/target.png</href>
        </Icon>
      </IconStyle>
    </Style>
    <Style id="safeDevice">
      <IconStyle>
        <color>ff00ff00</color>
        <scale>0.8</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/paddle/wht-blank.png</href>
        </Icon>
      </IconStyle>
    </Style>`;

  const kmlFooter = `
  </Document>
</kml>`;

  const placemarks = trackedDevices.map(d => {
    const style = d.threatLevel === ThreatLevel.HIGH || d.threatLevel === ThreatLevel.SUSPICIOUS 
      ? '#highThreat' 
      : '#safeDevice';
    
    const description = `
      MAC: ${d.mac}
      Vendor: ${d.vendor || 'Unknown'}
      SSID: ${d.ssid || 'Hidden'}
      Probes: ${d.probedSSIDs.join(', ')}
      Persistence: ${Math.round(d.persistenceScore * 100)}%
      First Seen: ${new Date(d.firstSeen).toISOString()}
      Last Seen: ${new Date(d.lastSeen).toISOString()}
    `;

    return `
    <Placemark>
      <name>${d.ssid || d.mac}</name>
      <description>${description.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</description>
      <styleUrl>${style}</styleUrl>
      <Point>
        <coordinates>${d.gps?.lng},${d.gps?.lat},0</coordinates>
      </Point>
    </Placemark>`;
  }).join('');

  return kmlHeader + placemarks + kmlFooter;
};

export const downloadKML = (devices: WifiDevice[]) => {
  const content = generateKML(devices);
  if (!content) {
    alert("No devices with GPS data to export.");
    return;
  }
  
  const blob = new Blob([content], { type: 'application/vnd.google-earth.kml+xml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `cyt-scan-${new Date().toISOString().slice(0,19).replace(/:/g,'-')}.kml`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};